# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb85e23553a42ca2afd1ea7270055fd0f203de66da25c06b534b19499fcc61541212a38ce03618b734f3feb40e5a7291459e2272d3c5c13d3141a6a6fe0786b4

test:
  secret_key_base: ce7ef5c4fed98982e8e9022286823a357080ee206572bfceb8199e6012b9c8c504ff5bef8c9620d054e67a07f14c2090b9f2fe2674c614b19fdb987ed25b044e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
